spring:
  application:
    api-prefix: ${API_PREFIX:/api/v1}
    name: spring-boot-rest-api
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: ${API_PORT:3000}

payment:
  vnPay:
    url: ${PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    tmnCode: ${TMN_CODE:58X4B4HP}
    secretKey: ${SECRET_KEY:VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ}
    returnUrl: ${RETURN_URL:http://localhost:3000/api/v1/payment/vn-pay-callback}
    version: ${VERSION:2.1.0}
    command: ${COMMAND:pay}
    orderType: ${ORDER_TYPE:other}
  momo:
#    partner-code: MOMO
#    return-url: http://localhost:3000/api/v1/payment/momo/callback
#    end-point: https://test-payment.momo.vn/v2/gateway/api/create
#    ipn-url: http://localhost:3000/api/v1/payment/momo/ipn-handler
#    access-key: F8BBA842ECF85
#    secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
#    request-type: captureWallet

      partner-code: MOMOLRJZ20181206
      access-key: mTCKt9W3eU1m39TW
      secret-key: SetA5RDnLHvt51AULf51DyauxUo3kDU6
      return-url: http://localhost:3000/api/v1/payment/callback
#      return-url: https://technihongo-hueze5fkd5g2f7bk.centralindia-01.azurewebsites.net/api/v1/payment/callback
      ipn-url: http://localhost:3000/api/v1/payment/ipn-handler
#      ipn-url: https://technihongo-hueze5fkd5g2f7bk.centralindia-01.azurewebsites.net/api/v1/payment/ipn-handler
      request-type: captureWallet
      endpoint: https://test-payment.momo.vn/v2/gateway/api
      create-url: /create
      skip-signature-verification: true




#      partner-code: MOMOLRJZ20181206
#      access-key: mTCKt9W3eU1m39TW
#      secret-key: SetA5RDnLHvt51AULf51DyauxUo3kDU6
#      return-url: http://localhost:3000/api/v1/payment/momo/callback
#      ipn-url: http://localhost:3000/api/v1/payment/momo/ipn-handler
#      request-type: captureWallet
#      endpoint: https://test-payment.momo.vn/v2/gateway/api
#      create-url: /create

  zaloPay:
    app-id: 2553
    key1: PcY4iZIKFCIdgZvA6ueMcMHHUbRLYjPL
    key2: kLtgPl8HHhfvMuDHPwKfgfsY4Ydm9eIz
    endpoint: https://sb-openapi.zalopay.vn/v2
    return-url: http://localhost:3000/api/v1/payment/callback
#    return-url: https://technihongo-hueze5fkd5g2f7bk.centralindia-01.azurewebsites.net/api/v1/payment/callback
    ipn-url: http://localhost:3000/api/v1/payment/ipn-handler
#    ipn-url: https://technihongo-hueze5fkd5g2f7bk.centralindia-01.azurewebsites.net/api/v1/payment/ipn-handler
    create-url: /create
#    skip-signature-verification: true